"""
Dashboard Routes - Aggregated stats and analytics endpoints.
"""
from datetime import datetime, timedelta

from fastapi import APIRouter, Depends
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.models.models import Lead, LeadStatus, LeadSource, Agent, Campaign, CampaignStatus, AnalyticsEvent

router = APIRouter(prefix="/api/dashboard", tags=["dashboard"])


@router.get("/stats")
async def get_dashboard_stats(db: AsyncSession = Depends(get_db)):
    """Get comprehensive dashboard statistics."""
    today = datetime.utcnow().replace(hour=0, minute=0, second=0, microsecond=0)
    seven_days_ago = datetime.utcnow() - timedelta(days=7)

    # Total leads
    total_result = await db.execute(select(func.count(Lead.id)))
    total_leads = total_result.scalar() or 0

    # New leads today
    today_result = await db.execute(
        select(func.count(Lead.id)).where(Lead.created_at >= today)
    )
    new_today = today_result.scalar() or 0

    # New leads this week
    week_result = await db.execute(
        select(func.count(Lead.id)).where(Lead.created_at >= seven_days_ago)
    )
    new_this_week = week_result.scalar() or 0

    # Qualified leads
    qualified_result = await db.execute(
        select(func.count(Lead.id)).where(Lead.status == LeadStatus.QUALIFIED)
    )
    qualified = qualified_result.scalar() or 0

    # Conversion rate
    won_result = await db.execute(
        select(func.count(Lead.id)).where(Lead.status == LeadStatus.CLOSED_WON)
    )
    won = won_result.scalar() or 0
    conversion_rate = round((won / total_leads) * 100, 1) if total_leads > 0 else 0

    # Active agents
    active_agents_result = await db.execute(
        select(func.count(Agent.id)).where(Agent.is_enabled == True)
    )
    active_agents = active_agents_result.scalar() or 0

    # Active campaigns
    active_campaigns_result = await db.execute(
        select(func.count(Campaign.id)).where(Campaign.status == CampaignStatus.ACTIVE)
    )
    active_campaigns = active_campaigns_result.scalar() or 0

    # Average lead score
    avg_score_result = await db.execute(
        select(func.avg(Lead.score)).where(Lead.score > 0)
    )
    avg_score = round(avg_score_result.scalar() or 0, 2)

    # Leads by source
    source_result = await db.execute(
        select(Lead.source, func.count(Lead.id)).group_by(Lead.source)
    )
    by_source = {
        (row[0].value if hasattr(row[0], "value") else str(row[0])): row[1]
        for row in source_result.all()
    }

    # Leads by status
    status_result = await db.execute(
        select(Lead.status, func.count(Lead.id)).group_by(Lead.status)
    )
    by_status = {
        (row[0].value if hasattr(row[0], "value") else str(row[0])): row[1]
        for row in status_result.all()
    }

    # Daily lead trend (last 14 days)
    fourteen_days_ago = datetime.utcnow() - timedelta(days=14)
    daily_result = await db.execute(
        select(func.date(Lead.created_at), func.count(Lead.id))
        .where(Lead.created_at >= fourteen_days_ago)
        .group_by(func.date(Lead.created_at))
        .order_by(func.date(Lead.created_at))
    )
    daily_trend = [{"date": str(row[0]), "count": row[1]} for row in daily_result.all()]

    # Recent leads
    recent_result = await db.execute(
        select(Lead).order_by(Lead.created_at.desc()).limit(10)
    )
    recent_leads = [
        {
            "id": l.id,
            "name": f"{l.first_name or ''} {l.last_name or ''}".strip() or "Unknown",
            "email": l.email,
            "company": l.company,
            "score": l.score,
            "status": l.status.value if hasattr(l.status, "value") else str(l.status),
            "source": l.source.value if hasattr(l.source, "value") else str(l.source),
            "created_at": l.created_at.isoformat(),
        }
        for l in recent_result.scalars().all()
    ]

    # Total leads generated by agents
    agents_result = await db.execute(
        select(func.sum(Agent.leads_generated))
    )
    agent_total_leads = agents_result.scalar() or 0

    return {
        "total_leads": total_leads,
        "new_today": new_today,
        "new_this_week": new_this_week,
        "qualified_leads": qualified,
        "conversion_rate": conversion_rate,
        "active_agents": active_agents,
        "active_campaigns": active_campaigns,
        "average_score": avg_score,
        "leads_by_source": by_source,
        "leads_by_status": by_status,
        "daily_trend": daily_trend,
        "recent_leads": recent_leads,
        "agent_total_leads": agent_total_leads,
    }
